services:
  - type: web
    name: multi-agent
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
